package com.salesmentor.salescase.application;
import com.salesmentor.experience.application.*; import com.salesmentor.experience.domain.*; import com.salesmentor.salescase.domain.*;
import org.springframework.beans.factory.annotation.Autowired; import org.springframework.beans.factory.annotation.Qualifier; import org.springframework.stereotype.Service;
import java.time.Duration;
import java.nio.charset.StandardCharsets; import java.security.MessageDigest; import java.util.*; import java.util.concurrent.*;
import java.util.concurrent.atomic.*;
@Service public class SalesCaseApplicationService {
 private final SalesCaseRepository cases; private final ExperienceRepository experiences; private final ExperienceExtractor extractor; private final ExperienceSchemaValidator schema; private final EvidenceGroundingValidator grounding; private final Executor executor; private final Duration extractionTimeout;
 @Autowired public SalesCaseApplicationService(SalesCaseRepository c,ExperienceRepository e,ExperienceExtractor x,ExperienceSchemaValidator s,EvidenceGroundingValidator g,@Qualifier("experienceExecutor") Executor q){this(c,e,x,s,g,q,Duration.ofSeconds(15));}
 public SalesCaseApplicationService(SalesCaseRepository c,ExperienceRepository e,ExperienceExtractor x,ExperienceSchemaValidator s,EvidenceGroundingValidator g,Executor q,Duration timeout){cases=c;experiences=e;extractor=x;schema=s;grounding=g;executor=q;extractionTimeout=Objects.requireNonNull(timeout);}
 public SalesCase importCase(SalesCase v){SalesCase s=cases.save(v);submit(s.id());return s;}
 public void retry(Long id){SalesCase v=get(id);if(v.status()!=SalesCase.Status.EXTRACT_FAILED)throw new CaseStateConflictException("\u6848\u4F8B\u72B6\u6001\u5DF2\u53D8\u5316");if(!cases.compareAndSetStatus(id,SalesCase.Status.EXTRACT_FAILED,SalesCase.Status.IMPORTED,null))throw new CaseStateConflictException("\u6848\u4F8B\u72B6\u6001\u5DF2\u53D8\u5316");submit(id);}
 private void submit(Long id){AtomicBoolean timedOut=new AtomicBoolean();AtomicReference<FutureTask<Void>> taskRef=new AtomicReference<>();AtomicReference<CompletableFuture<Void>> watchdogRef=new AtomicReference<>();Object completionLock=new Object();FutureTask<Void> task=new FutureTask<>(()->{extract(id,timedOut,taskRef,watchdogRef,completionLock);return null;});taskRef.set(task);try{executor.execute(task);}catch(RejectedExecutionException e){cases.compareAndSetStatus(id,SalesCase.Status.IMPORTED,SalesCase.Status.EXTRACT_FAILED,"SYSTEM_BUSY");throw new IllegalStateException("SYSTEM_BUSY");}}
 private void extract(Long id,AtomicBoolean timedOut,AtomicReference<FutureTask<Void>> taskRef,AtomicReference<CompletableFuture<Void>> watchdogRef,Object completionLock){if(!cases.compareAndSetStatus(id,SalesCase.Status.IMPORTED,SalesCase.Status.EXTRACTING,null))return;CompletableFuture<Void> watchdog=CompletableFuture.runAsync(()->{synchronized(completionLock){if(cases.compareAndSetStatus(id,SalesCase.Status.EXTRACTING,SalesCase.Status.EXTRACT_FAILED,"EXTRACTION_TIMEOUT")){timedOut.set(true);FutureTask<Void> task=taskRef.get();if(task!=null)task.cancel(true);}}},CompletableFuture.delayedExecutor(extractionTimeout.toMillis(),TimeUnit.MILLISECONDS));watchdogRef.set(watchdog);try{SalesCase v=get(id);var b=extractor.extract(new ExperienceExtractor.ExtractionCommand(id,v.content(),v.industry(),v.salesStage(),v.customerRole()));if(timedOut.get())return;schema.validateBatch(b);int schemaRejected=0,evidenceRejected=0;for(var d:b.drafts()){if(timedOut.get())return;EvidenceGroundingValidator.Evidence ev;try{schema.validateDraft(d);}catch(IllegalArgumentException ex){schemaRejected++;continue;}try{ev=grounding.evidence(v.content(),d.evidenceQuote());}catch(IllegalArgumentException ex){evidenceRejected++;continue;}synchronized(completionLock){if(timedOut.get())return;experiences.save(unit(id,d,ev));}}synchronized(completionLock){if(timedOut.get())return;int rejected=schemaRejected+evidenceRejected;String error=rejected==0?null:"rejected="+rejected+"; schema="+schemaRejected+"; evidence="+evidenceRejected;cases.compareAndSetStatus(id,SalesCase.Status.EXTRACTING,SalesCase.Status.EXTRACTED,error);}}catch(Exception e){String m=e.getMessage()==null?"EXTRACTION_FAILED":e.getMessage();m=m.replaceAll("(?i)(api[-_ ]?key|token|password)\\s*[:=]\\s*\\S+","$1=[REDACTED]");synchronized(completionLock){cases.compareAndSetStatus(id,SalesCase.Status.EXTRACTING,SalesCase.Status.EXTRACT_FAILED,m.substring(0,Math.min(900,m.length())));}}finally{watchdog.cancel(false);}}
 private ExperienceUnit unit(Long id,ExperienceExtractor.ExperienceDraft d,EvidenceGroundingValidator.Evidence e){return new ExperienceUnit(null,id,d.scenarioType(),d.objectionType(),d.salesStage(),d.customerRole(),d.triggerText(),d.strategySummary(),d.recommendedQuestion(),d.evidenceQuote(),e.start(),e.end(),d.applicability(),hash(d),ExperienceUnit.ReviewStatus.GENERATED,ExperienceUnit.IndexStatus.NOT_INDEXED,null,extractor.getClass().getSimpleName().contains("Local")?"local":"cloud","experience-extract-v1",null,null,0,null,null);}
 private String hash(Object v){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(v.toString().getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
 public SalesCase get(Long id){return cases.findById(id).orElseThrow(()->new IllegalArgumentException("案例不存在"));} public List<ExperienceUnit> experiences(Long id){get(id);return experiences.findByCaseId(id);}
}
