CREATE TABLE sm_sales_case (
    id              BIGINT PRIMARY KEY,
    external_key    VARCHAR(64) NULL,
    title           VARCHAR(200) NOT NULL,
    source_type     VARCHAR(32) NOT NULL,
    source_uri      VARCHAR(500) NULL,
    industry        VARCHAR(64) NULL,
    sales_stage     VARCHAR(32) NULL,
    customer_role   VARCHAR(64) NULL,
    content         MEDIUMTEXT NOT NULL,
    status          VARCHAR(32) NOT NULL,
    extract_error   VARCHAR(1000) NULL,
    version         INT NOT NULL DEFAULT 0,
    created_at      DATETIME(3) NOT NULL,
    updated_at      DATETIME(3) NOT NULL,
    UNIQUE KEY uk_sales_case_external_key (external_key),
    KEY idx_sales_case_status (status),
    KEY idx_sales_case_metadata (industry, sales_stage, customer_role)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE sm_experience_unit (
    id                    BIGINT PRIMARY KEY,
    case_id               BIGINT NOT NULL,
    scenario_type         VARCHAR(32) NOT NULL,
    objection_type        VARCHAR(32) NULL,
    sales_stage           VARCHAR(32) NULL,
    customer_role         VARCHAR(64) NULL,
    trigger_text          VARCHAR(500) NOT NULL,
    strategy_summary      VARCHAR(1000) NOT NULL,
    recommended_question  VARCHAR(500) NULL,
    evidence_quote        VARCHAR(2000) NOT NULL,
    evidence_start        INT NOT NULL,
    evidence_end          INT NOT NULL,
    applicability         VARCHAR(1000) NULL,
    content_hash          CHAR(64) NOT NULL,
    review_status         VARCHAR(32) NOT NULL,
    index_status          VARCHAR(32) NOT NULL,
    vector_ref            VARCHAR(128) NULL,
    extraction_model      VARCHAR(64) NULL,
    prompt_version        VARCHAR(32) NOT NULL,
    reviewed_by           BIGINT NULL,
    reviewed_at           DATETIME(3) NULL,
    version               INT NOT NULL DEFAULT 0,
    created_at            DATETIME(3) NOT NULL,
    updated_at            DATETIME(3) NOT NULL,
    CONSTRAINT fk_experience_case FOREIGN KEY (case_id) REFERENCES sm_sales_case(id),
    UNIQUE KEY uk_experience_case_hash (case_id, content_hash),
    KEY idx_experience_publish (review_status, index_status),
    KEY idx_experience_metadata (scenario_type, objection_type, sales_stage)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE sm_knowledge_document (
    id               BIGINT PRIMARY KEY,
    title            VARCHAR(200) NOT NULL,
    document_type    VARCHAR(32) NOT NULL,
    source_name      VARCHAR(200) NULL,
    content          MEDIUMTEXT NOT NULL,
    content_hash     CHAR(64) NOT NULL,
    status           VARCHAR(32) NOT NULL,
    index_status     VARCHAR(32) NOT NULL,
    vector_namespace VARCHAR(64) NOT NULL DEFAULT 'product',
    created_at       DATETIME(3) NOT NULL,
    updated_at       DATETIME(3) NOT NULL,
    UNIQUE KEY uk_knowledge_hash (content_hash),
    KEY idx_knowledge_status (status, index_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE sm_review_task (
    id                    BIGINT PRIMARY KEY,
    request_id            VARCHAR(64) NOT NULL,
    user_id               BIGINT NULL,
    session_id            VARCHAR(64) NULL,
    industry              VARCHAR(64) NULL,
    sales_stage           VARCHAR(32) NULL,
    customer_role         VARCHAR(64) NULL,
    conversation_content  MEDIUMTEXT NOT NULL,
    review_goal           VARCHAR(500) NULL,
    status                VARCHAR(32) NOT NULL,
    plan_json             JSON NULL,
    report_json           JSON NULL,
    partial_reason        VARCHAR(1000) NULL,
    started_at            DATETIME(3) NULL,
    finished_at           DATETIME(3) NULL,
    created_at            DATETIME(3) NOT NULL,
    updated_at            DATETIME(3) NOT NULL,
    UNIQUE KEY uk_review_request_id (request_id),
    KEY idx_review_user_time (user_id, created_at),
    KEY idx_review_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE sm_agent_trace (
    id              BIGINT PRIMARY KEY,
    task_id         BIGINT NOT NULL,
    step_no         INT NOT NULL,
    step_type       VARCHAR(32) NOT NULL,
    tool_name       VARCHAR(64) NULL,
    input_json      JSON NULL,
    output_summary  VARCHAR(2000) NULL,
    evidence_ids    JSON NULL,
    duration_ms     BIGINT NOT NULL,
    status          VARCHAR(32) NOT NULL,
    error_code      VARCHAR(64) NULL,
    created_at      DATETIME(3) NOT NULL,
    CONSTRAINT fk_trace_task FOREIGN KEY (task_id) REFERENCES sm_review_task(id),
    UNIQUE KEY uk_trace_task_step (task_id, step_no),
    KEY idx_trace_task (task_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
